<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container70gq2wc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container70gq2wc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container70gq2wc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container70gq2wc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container70gq2wc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '70gq2wc',
    'container.build_id' => '57520d39',
    'container.build_time' => 1605281924,
], __DIR__.\DIRECTORY_SEPARATOR.'Container70gq2wc');
